economy:
  enabled: true

  # Initial balance for new player accounts
  initial-bal: 100

  # Currency symbol
  symbol: "$"
  # Currency name
  name-singular: "dollar"
  name-plural: "dollars"

  # Enable or disable commands
  commands:
    baltop: false
    deposit: true
    withdraw: true

permission:
  enabled: false

chat:
  enabled: false